# Generated by Django 5.2.16 on 2026-07-24 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_tag_category_article_categories_article_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleSimilarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("score", models.FloatField()),
                ("rank", models.PositiveSmallIntegerField()),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarity_entries",
                        to="articles.article",
                    ),
                ),
                (
                    "related_article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="articles.article",
                    ),
                ),
            ],
            options={
                "verbose_name": "кэш похожих статей",
                "verbose_name_plural": "кэш похожих статей",
                "ordering": ["article", "rank"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("article", "rank"), name="unique_article_similarity_rank"
                    )
                ],
            },
        ),
    ]
