# Generated by Django 5.2.16 on 2026-08-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_articlesimilarity"),
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="visible_departments",
            field=models.ManyToManyField(
                blank=True, related_name="articles_restricted_to", to="departments.department"
            ),
        ),
    ]
