# Generated by Django 5.2.16 on 2026-07-24 10:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("articles", "0003_articlesimilarity"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("chunk_index", models.PositiveIntegerField()),
                ("text", models.TextField()),
                ("embedding", models.BinaryField()),
                ("embedding_model", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="articles.article",
                    ),
                ),
            ],
            options={
                "verbose_name": "фрагмент статьи для ИИ-поиска",
                "verbose_name_plural": "фрагменты статей для ИИ-поиска",
                "ordering": ["article", "chunk_index"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("article", "chunk_index"), name="unique_article_chunk_index"
                    )
                ],
            },
        ),
    ]
