# Generated by Django 5.2.16 on 2026-07-27 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_articlesimilarity"),
        ("assistant", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assistantsettings",
            name="local_ai_article_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="assistantsettings",
            name="local_ai_chunk_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="assistantsettings",
            name="local_ai_is_training",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assistantsettings",
            name="local_ai_last_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assistantsettings",
            name="local_ai_trained_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assistantsettings",
            name="local_ai_trained_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ArticleChunkEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("chunk_index", models.PositiveIntegerField()),
                ("text", models.TextField()),
                ("embedding", models.BinaryField()),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunk_embeddings",
                        to="articles.article",
                    ),
                ),
            ],
            options={
                "verbose_name": "фрагмент статьи (локальный ИИ)",
                "verbose_name_plural": "фрагменты статей (локальный ИИ)",
                "ordering": ["article_id", "chunk_index"],
            },
        ),
    ]
