# Generated by Django 5.2.16 on 2026-07-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0002_assistantsettings_local_ai_article_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistantsettings",
            name="local_ai_log",
            field=models.TextField(blank=True, default=""),
        ),
    ]
